[build]
  functions = ".netlify/functions"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cross-Origin-Opener-Policy= "unsafe-none"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200