export const CATEGORY_ACTION_TYPES = {
  SET_CATEGORIES_START: "SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_FAILURE: "SET_CATEGORIES_FAILURE",
};

export const CATEGORY_INITIAL_STATE = {
  categories: [],
  isLoading: false,
  error: null,
};
